name: "Run Python Script"
description: "Run a custom python snippet inside a workflow file"
inputs:
  script:
    description: "Python script"
    required: true
  fail-on-error:
    description: "Fail step if the return code from running the script is non-zero"
    required: false
    default: true
  util:
    description: "Include utility functions"
    required: false
    default: true
outputs:
  stdout:
    description: "Program stdout"
  stderr:
    description: "Program stderr"
  error:
    description: "A string of 'true' or 'false' that tells if there were errors, use in conjunction with the fail-on-error input"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: "purple"
  icon: "play"
